# Site settings
title: techmunich
url: "http://techmunich.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# GH Metadata Settings
repository: techmunich/techmunich.io

# Gems
gems: ['jekyll-github-metadata']
