# Site settings
title: techmunich

# Build settings
markdown: kramdown

# GH Metadata Settings
repository: techmunich/techmunich.io

# Gems
gems:
 - jekyll-github-metadata
 - jekyll-assets
 - octopress-autoprefixer
